name: Build AIR Simulator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # THE FIX 1: We use the fast, available queues!
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup MSVC Compiler
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt 6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3' 
        host: ${{ runner.os == 'Windows' && 'windows' || runner.os == 'macOS' && 'mac' || 'linux' }}
        target: 'desktop'
        arch: ${{ runner.os == 'Windows' && 'win64_msvc2019_64' || '' }} 
        setup-python: 'false' 

    - name: Build on Linux & macOS
      if: runner.os != 'Windows'
      env:
        # THE FIX 2: This forces the new Mac server to make the app backward-compatible for older Macs!
        MACOSX_DEPLOYMENT_TARGET: "11.0" 
      run: |
        qmake
        make -j4

    - name: Build on Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        qmake
        nmake
